export { default as Bird } from './Bird.jsx'
export { default as Island } from './Island.jsx'
export { default as Plane } from './Plane.jsx'
export { default as Sky } from './Sky.jsx'
export { default as Fox } from './Fox.jsx'
